### ISSUE TITLE
OSCI CI dashboard to have a link to Log Detective submission page

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/log-detective-website#122]
The same thing as Copr, but do it in CI dashboard

We should work with the OSCI team on this

![image](https://github.com/fedora-copr/log-detective-website/assets/1662493/b781b5b2-d6c0-4438-86c5-1bcb7b4cd299)

**Comment by praiskup** [comment]
triage time: Do you have a link to the OSCI dashboard?  Is this related to TF?

**Comment by TomasTomecek** [comment]
http://dashboard.osci.redhat.com/

I'm not aware of a public deployment.

**Comment by praiskup** [comment]
Log Detective reads the logs from the external service, and it must be public.... this is going to be problematic

**Comment by TomasTomecek** [comment]
Since this is unclear, I am going to close. Once we have a more concrete idea, we can open a specific issue for integration.
