### ISSUE TITLE
Switching between log source tabs is unpredictable

### ISSUE THREAD

**Issue by SpyTec** [fedora-copr/log-detective-website#123]
Currently with the different tabs like Copr, Koji, Packit, etc. are not doing what I would expect them to.

Two issues I've noticed:

1: Sometimes when a tab is clicked, nothing will happen
![image](https://github.com/fedora-copr/log-detective-website/assets/6598829/c76038b8-9600-4688-b39b-6ee332097d59)

2: Images are not updated with the page, with enough delay to cause confusion
![image](https://github.com/fedora-copr/log-detective-website/assets/6598829/6250271b-686d-4028-b424-ea333df59e11)

3: Moving backwards and forwards in browser history does not change the selected tab

4: If moving backwards in browser history from something like `#packit` -> `#koji` then selecting a different tab than those two, like `#copr`, it will select the `#koji` tab while updating the URL to be `#copr`

Console is empty, nothing to report there. Not able to contribute as I don't know ClosureScript

**Comment by praiskup** [comment]
We know about this problem, and it is not always reproducible :-(

Excactly because there's nothing in the console, it is very hard-to-catch issue.  If you have more info, please help.

**Comment by nikromen** [comment]
also this happens only in firefox so this can be some issue with different browser engines :/

**Comment by SpyTec** [comment]
I don't even know where to approach for ClosureScript unfortunately. If possible record the render between tabs, I know React Developer tools browser extension can do this for React projects. But that should be able to indicate how the renders are done and if there's a way to do the renders better in ClosureScript documentation

For the tabs issue I'd also suspect it to be a rendering issue
