### ISSUE TITLE
Koji annotation page has no 'Anotate selection' button

### ISSUE THREAD

**Issue by ppisar** [fedora-copr/log-detective-website#126]
Koji annotation page <https://log-detective.com/contribute/koji/2441874/x86_64#> reads in the Instructions column:

> Anotate snippets by selecting them, and clicking 'Anotate selection'

But I cannot see any buttong on the page labeled "Anotate selection". I can only see "Add" button in "Interesting snippets:" section and "Submit" button at the end of the page.

**Comment by nikromen** [comment]
Closed with #128
