### ISSUE TITLE
pydantic v2 release

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/log-detective-website#132]
with F40 there's been migration to pydantic v2. There are some breaking changes - I didn't check if we need to do something about them.

We have two options:
- check what needs to be changed and change it to v2
- or we can still use v1 by using `from pydatic.v1 import ...`

**Comment by praiskup** [comment]
Is this related to linting-only, or is it an API-related issue?

**Comment by Bvr4** [comment]
Hello, there will be some adjustment to do.

For instance the root_validator function is depreciated. I may be able to help you on that if you want to.

**Comment by nikromen** [comment]
thanks for identifying what is deprecated - I'll take care of the rest with migrating our instance to fedora-40, thanks!
