### ISSUE TITLE
Upload fixed data to production

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/log-detective-website#152]
The production instance currently has data with broken snippet indexes. When I fixed the data, I did it in a separate git repository but never actually uploaded them back to production because there was no need. Now we need it otherwise the review page will show nonsense.

![Screenshot_2024-08-09_12-43-17](https://github.com/user-attachments/assets/e50877a9-fd14-4fa7-8c60-cc17dada86ee)

We need to fix this before announcing the review feature.

**Comment by TomasTomecek** [comment]
I took the data from the git repo Kuba sent me and crafted a new `results/` dir in production that contained the fixed data + all other entries from old results. This is how it looks now:

```
sh-5.2$ ls -1
fixed-results.tar.gz
results
reviews
letsencrypt
results-old-wrong

sh-5.2$ ls -la results/ | wc -l
65
```

@FrostyX can you please verify I did it correctly?

**Comment by FrostyX** [comment]
This looks good, thank you very much @TomasTomecek.

> sh-5.2$ ls -la results/ | wc -l
> 65

In the ["fixed repo"](https://github.com/copr-private/log-detective-fixed-snippets) there is only 35 directories, so there is quite a lot of new data. Which should be correct because we already have the fix in production but it may be worth taking a look at a few new results.

**Comment by TomasTomecek** [comment]
@FrostyX thanks for checking! I am going to close this then.
