### ISSUE TITLE
Link for packit build (koji) redirects to copr builds, not koji builds

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/log-detective-website#22]
![Screenshot_20231027_131819](https://github.com/fedora-copr/lightspeed-build-website/assets/70757578/fdab8c25-e207-4fad-9426-140a8e4a108e)

the link in instructions redirects to copr builds every time even when this packit build should redirect to koji builds

**Comment by nikromen** [comment]
Showing the actual build in packit dashboard can be done this way:
- copr builds: https://dashboard.packit.dev/results/copr-builds/{packit_id}
- koji builds: https://dashboard.packit.dev/results/koji-builds/{packit_id}

deciding whether the build is koji or copr based only on packit_id is harder. However what I do on backend is trying to get copr build for `packit_id` from packit API. If I don't get 2XX response, then I assume it's koji build (note that the IDs may overlap but since the difference between packit_id for koji and copr is enormous, the small IDs for koji builds no longer exists for copr builds so I assume it's safe).

@lachmanfrantisek do you know whether a more convenient way to differentiate koji and copr builds based only on packit_id exists?

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek do you know whether a more convenient way to differentiate koji and copr builds based only on packit_id exists?

What is actually the full use case/process here? What do you have and what do you need?..;)

A few notes:
* The `packit_id` is not shared between Copr and Koji builds. It might work just because we have many more Copr builds. 
* Through the Packit's API, you can get a Copr ID from Packit ID. There is no endpoint for reverse mapping.

The Packit API can be enhanced -- maybe we can add a new endpoint so you don't need to hack something outside of Packit.

**Comment by nikromen** [comment]
Thanks for your response, Franto. I'll summarize out conversation from Monday's mtg so we have an update here:
  - the copr and koji id may overlap but the copr id is much bigger than koji so those logs in copr with current koji ids no longer exist
  - ideally, the solution would be clickable switch between koji and copr on packit tab (but it works as it is so it's just nice to have)
  - we don't need any actions from packit team to resolve this

**Comment by lachmanfrantisek** [comment]
Thanks Jirko for summarising this! Maybe one missing note that starting with Copr builds, for now, should be really fine. There are not many users of upstream Koji scratch builds. With downstream Koji builds, we are just working on saving them into the database.

**Comment by lachmanfrantisek** [comment]
Just spotted this today and found this issue when wanting to create a new one..;)

![image](https://github.com/fedora-copr/log-detective-website/assets/20214043/05ab3d1c-13ab-42e6-ad2e-7d037f5edb12)

The link as is is currently a bit misleading so I would either remove it or blindly use `https://dashboard.packit.dev/results/copr-builds/{packit_id}`. (Don't you already know what type of build this is when you're showing the logs to the user?)
