### ISSUE TITLE
Add consent with processing

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/log-detective-website#25]
We should have somewhere written that user agree with processing the data and agrees with teaching AI.

**Comment by FrostyX** [comment]
Do you mean a checkbox each time you submit builds? Similarly how eshops have checkboxes for using your personal data? Or just a simple text on the page saying that by submitting you agree with processing and teaching AI?

**Comment by xsuchy** [comment]
Simple text will be sufficient. I guess.

**Comment by xsuchy** [comment]
I propose the wording
```
By submitting this form, you agree that your input can be used for teaching AI and that the data are available under WTFPL license.
```

**Comment by jpodivin** [comment]
> WTFPL license

I would advise to use a license that's perhaps a bit more suited to the task, such as CDLA.[0]

[0] https://cdla.dev/
