### ISSUE TITLE
Data backups in production

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/log-detective-website#33]
Do we have backups in CommuniShift for free, administered by Fedora Infra team, or do we have to setup them on our own?

**Comment by FrostyX** [comment]
@nirik can you please let us know?

**Comment by nikromen** [comment]
#62 introduces cronjob that tars our data every day - only thing now needed is to add a functionality that will upload this tar somewhere

**Comment by FrostyX** [comment]
> that will upload this tar somewhere

I would go the other way around and set up something, that will periodically download the tarball

**Comment by FrostyX** [comment]
We can add something like this to Cron:

```
wget https://log-detective.com/download -O $(date +"log-detective-%Y-%m-%d-%s.tar.gz")
```

**Comment by praiskup** [comment]
Done here: https://pagure.io/fedora-infra/ansible/c/1a38d112c72b9c297fe428b3f0c09f406a7c300c?branch=main
