### ISSUE TITLE
Offer download of the raw collected data

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/log-detective-website#49]
We should have link somewhere to download collected data in a raw form. 
It can be a daily updated tarball. Does not need to be too polished. Only few people will likely use this.

**Comment by nikromen** [comment]
just for confirmation - collected data == feedbacks stored on backend from users (without reviews)?

**Comment by xsuchy** [comment]
IMO - everything. As much as possible.

**Comment by FrostyX** [comment]
Triage time: We want to deploy another container in OpenShift that would read-only mount the data volume, and run httpd to serve directory listing with the data.
