### ISSUE TITLE
Use nginx for deployment

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/log-detective-website#61]
gunicorn works well but doesn't support 2 domains, which we have

Let's have an nginx in front of guni where we accept connections to both of the domains

Don't forget to create a route for logdetective.com too

**Comment by nikromen** [comment]
hmmm, not sure but I think this could be solved by adding cors to API

```py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
ORIGINS = "https://www.logdetective.com,https://www.log-detective.com"

app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://www.logdetective.com", "https://www.log-detective.com"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

nginx deployment sauce: https://www.uvicorn.org/deployment/#running-behind-nginx https://docs.gunicorn.org/en/latest/deploy.html

**Comment by FrostyX** [comment]
I know close to nothing about `fastapi` so you may be right. But CORS are usually related to what addresses can the JavaScript code communicate with.

**Comment by nikromen** [comment]
ah so cors won't help.

I also found a way how to "merge" two certificates into one - maybe https://community.letsencrypt.org/t/host-multiple-domains-with-a-single-certificate/20917/4 will help?

**Comment by TomasTomecek** [comment]
[The wildcard certs](https://en.wikipedia.org/wiki/Wildcard_certificate) work for subdomains of a single domain, basically `*.example.com`. 

It would be amazing if we could merge the certificates for log-detective and logdetective into a single certificate file.

Also depends if gunicorn could work with such a certificate.

**Comment by nikromen** [comment]
+ redirect to https

**Comment by nikromen** [comment]
tomas managed to merge those certificates \o/ #68

**Comment by TomasTomecek** [comment]
I think that longterm we'll need a proper web server between the openshift route and the application server (gunicorn) but for now, @nikromen is right that the problem is resolved

**Comment by praiskup** [comment]
The log-detective now redirects to https automatically, and logdetective redirects to  log-detective.com. Only www.log-detective.com -> log-detective.com remains.

**Comment by nikromen** [comment]
> I think that longterm we'll need a proper web server between the openshift route and the application server (gunicorn) but for now, @nikromen is right that the problem is resolved

I stored my WIP nginx configuration I had so once needed one can take a look and maybe copy something from https://github.com/nikromen/log-detective-website/commit/f75fd958d082e72d86fed47252d1580b2d44c150
