### ISSUE TITLE
flake8 complains about semicolon in string

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/log-detective-website#63]
`backend/api.py:270:53: E702 multiple statements on one line (semicolon)` in #62 - this shouldn't be an error since semicolon is in string. This error is not present when running pre-commit locally. This is perhaps some weird bug in our CI

**Comment by nikromen** [comment]
line commented with noqa, uncomment it once resolved

**Comment by FrostyX** [comment]
Triage: The `noqa` comment to disable the false-positive warning sounds good enough.
