### ISSUE TITLE
Downloads may block API

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/log-detective-website#65]
The download takes some time, we have 8 workers - 8 downloads close to each other (but I don't think it will be so demanding feature) -> API blocked for a while.

If this will sometimes happen:
- make the download endpoint asynchronous
- switch to uvicorn from gunicorn (uvicorn is asynchronous server, gunicorn not)
  - uvicorn has to be deployed in production via ngingx - #61 implements this

**Comment by praiskup** [comment]
We can set a limit per/route once the problem appears. Closing for now.
