### ISSUE TITLE
Create blogposts for log-detective

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/log-detective-website#67]
paste your ideas here

**Comment by FrostyX** [comment]
I am planning to do a 2-3 minute video for a general audience

**Comment by praiskup** [comment]
Pavel is going to write blog-post for copr.fedoraproject.org home page (the "news" section).

**Comment by nikromen** [comment]
I'll write announce email to fedora-devel

**Comment by praiskup** [comment]
tt: https://blog.tomecek.net/post/log-detective/

**Comment by FrostyX** [comment]
jkadlcik: https://www.youtube.com/watch?v=_-O7ryKCnlQ

**Comment by nikromen** [comment]
done 🍷
